### ISSUE TITLE
Support newer Ruby Versions

### ISSUE THREAD

**Issue by KaoruDev** [linemanjs/heroku-buildpack-lineman-ruby#3]
```
remote:  !     Invalid RUBY_VERSION specified: ruby-2.1.5
remote:  !     Valid versions: ruby-2.0.0, ruby-1.9.3, ruby-1.9.2, ruby-1.8.7, ruby-1.9.3-jruby-1.7.0, ruby-1.8.7-jruby-1.7.0, ruby-1.9.3-jruby-1.7.1, ruby-1.8.7-jruby-1.7.1, ruby-1.9.3-rbx-2.0.0dev, ruby-1.8.7-rbx-2.0.0dev
```

I have my heroku ENV `BUILDPACK_URL` env pointing to this repo and above is the error message I'm getting.

**Comment by KaoruDev** [comment]
I tried to [rebase this repo with heroku's newer version](https://github.com/KaoruDev/heroku-buildpack-lineman-ruby) of the ruby build pack and ended up getting this error:

```
remote:        module.js:340
remote:        throw err;
remote:        ^
remote:        Error: Cannot find module '/tmp/build_00480dd3ad4c774794794065591b68f2/frontend/node_modules/.bin/lineman'
remote:        at Function.Module._resolveFilename (module.js:338:15)
remote:        at Function.Module._load (module.js:280:25)
remote:        at Function.Module.runMain (module.js:497:10)
remote:        at startup (node.js:119:16)
remote:        at node.js:901:3
remote:        mv: cannot stat ‘/tmp/build_00480dd3ad4c774794794065591b68f2/frontend/dist/js/*.js’: No such file or directory
remote:        mv: cannot stat ‘/tmp/build_00480dd3ad4c774794794065591b68f2/frontend/dist/css/*.css’: No such file or directory
```

Not entirely sure what's going on =(

**Comment by searls** [comment]
I personally don't really understand what this repo is for. If you're using rails-lineman, by chance, I don't think it's necessary.

Looks like @theotherzach made it?

**Comment by KaoruDev** [comment]
@searls I'm working on a sinatra based app. We got a work around by building the dist files and committing them, not an ideal work flow tho.

**Comment by theotherzach** [comment]
@searls This was originally set up so we could get Exercism (a Sinatra app) to deploy to Herloku while using Lineman. This repo is going to be so out of date at this point that it should probably be shut down so nobody tries to use it.

**Comment by searls** [comment]
Unfortunately there's not a way to delist a repo without deleting it (and making future builds impossible for anyone using it)
